@startuml
'General ERD explanation
'An entity is a Table in the DB (think of an Excel table)
'Everything before the -- is the Primary Key, so a UID for an entry (Each user is identified by its email, no email twice)
'If an attribute starts with a *, its mandatory
'If not, its optional

'||- means exactly one
'|o- means zero or one
'}|- means one or more
'}o- means zero or more
'User ||--|{ Membership: This means a Membership entry has exactly one user, and a user has at least one Membership

entity User {
  'User has no username, only email
  'As email is unique, it can be ID
  * email
  --
  * password
  * created_at
}

entity Task {
  'Task has no unique property, so we generate an ID
  * id
  --
  * title
  * created_at
  * group_id
  * completed
  description
  due_date
  location
}

entity Group {
  * id
  --
  * name
  * created_at
  description
}

'Contributer, admin, etc...
entity Role {
  * name
  --
  * description
}

entity InvitationStatus {
  * name
  --
  * description
}

'Membership if accepted -> TRUE, Invitation if accpeted -> FALSE (so not accepted yet)
'By combining with Invitation, we make sure that a member_email and group_id combination is unique over the whole DB:
'So an invite is not possible if already member
'So an invite is not possivle if already an invite pending
'When invite accpeted -> just change accepted value
'When invite declined -> delete whole entry
'Inviter can be empty for the default group
entity Membership {
  * member_email
  * group_id
  --
  * invitation_status
  * role_name
  inviter_email
  invited_at
  joined_at
}

entity SoftwareLicense {
  * key
  --
  * created_at
  * used_status
}

User |o--o{ Membership : inviter
User ||--o{ Membership  : member
Membership }|--|| Group
Membership }o--|| Role
Membership }o--|| InvitationStatus
Task }o--|| Group
@enduml