@startsalt
{
  Title CULater

    {^Account Creation Page
      Email    | "Enter your email"
      Password | "Set your password"
      LicenseKey | "Input your license key"
      [Cancel] | [  Create   ]
    }

  {^Login Page
    Login    | "Enter your email"
    Password | "Enter your password"
    [Cancel] | [  Login   ]
  }

  {^Home Page
[Logout]
    + Feature 1: Task Container
[Add Task]
    + Feature 2: Group Container
[Add Group]
    + Feature 3: Invite Container
  }

  {^Task Creation
    TaskTitle       | "Task Title"
    Description | "Task Description"
    Due Date    | "Select due date"
Group    | "Select group"
    [Create Task] | [Cancel]
  }

  {^Group Creation
    Group Name | "Enter group name"
Description | "Enter description"
    [Create Group] | [Cancel]
  }

{^Task Groups
    + Task 1: |[Edit] | [Delete]
    + Task 2: |[Edit] | [Delete]
  }

  {^User Groups
    + Group 1: |[Manage] | [View Members] | [Leave Group]
    + Group 2: |[Manage] | [View Members] | [Leave Group]
  }

  {^Group Invitations
    + Invitation from Group A: | [Accept] | [Decline]
    + Invitation from Group B: | [Accept] | [Decline]
  }
}
@endsalt